package main

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/whitefirer/seneschal/workflow"
	"github.com/whitefirer/seneschal/workflow/ai"
)

// buildAssistantFromEnv creates an AI Assistant from environment variables,
// for commands (explain/fix/generate/chat) that need an LLM but are not tied
// to a specific workflow's ai: config. Returns a clear error if no key.
func buildAssistantFromEnv() (*ai.Assistant, error) {
	// Reuse the workflow/ai config: empty provider defaults to "anthropic",
	// which reads ANTHROPIC_API_KEY / DEEPSEEK_API_KEY + ANTHROPIC_BASE_URL.
	p, err := ai.BuildProvider(ai.Config{})
	if err != nil {
		return nil, fmt.Errorf("AI unavailable: %w", err)
	}
	return ai.NewAssistant(p), nil
}

// aiContext returns a context with a generous timeout for assistant calls.
func aiContext() (context.Context, context.CancelFunc) {
	return context.WithTimeout(context.Background(), 120*time.Second)
}

// ── explain ──────────────────────────────────────────────────────────────────

var explainCmd = &cobra.Command{
	Use:     "explain <file.yaml>",
	Short:   "Explain what a workflow does (Chinese)",
	GroupID: "ai",
	Args:    cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		return explainWorkflow(args[0])
	},
}

// explainWorkflow reads a workflow YAML file and prints a Chinese explanation
// of what it does, generated by the AI assistant. (Former cmdExplain.)
func explainWorkflow(filePath string) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("reading file: %w", err)
	}

	assistant, err := buildAssistantFromEnv()
	if err != nil {
		return err
	}
	ctx, cancel := aiContext()
	defer cancel()

	explanation, err := assistant.Explain(ctx, string(data))
	if err != nil {
		return err
	}
	fmt.Println(explanation)
	return nil
}

// ── fix ──────────────────────────────────────────────────────────────────────

var fixCmd = &cobra.Command{
	Use:     "fix <file.yaml>",
	Short:   "Fix workflow validation errors",
	GroupID: "ai",
	Args:    cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		return fixWorkflow(args[0])
	},
}

// fixWorkflow validates a workflow YAML and, if there are errors, asks the AI
// to produce a fixed version (printed to stdout for redirection). If the
// workflow is already valid, reports that and exits. (Former cmdFix.)
func fixWorkflow(filePath string) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("reading file: %w", err)
	}

	// Validate first.
	wf, perr := workflow.Parse(data)
	if perr == nil {
		errs := wf.Validate()
		if len(errs) == 0 {
			fmt.Fprintln(os.Stderr, "✅ Workflow is already valid; nothing to fix.")
			return nil
		}
		// Format validation errors for the model.
		var sb strings.Builder
		for _, e := range errs {
			fmt.Fprintf(&sb, "  - %v\n", e)
		}
		perr = fmt.Errorf("validation errors:\n%s", sb.String())
	}

	assistant, err := buildAssistantFromEnv()
	if err != nil {
		return err
	}
	ctx, cancel := aiContext()
	defer cancel()

	fixed, err := assistant.Fix(ctx, string(data), perr.Error())
	if err != nil {
		return err
	}
	// Print only the YAML so users can redirect: seneschal fix x.yaml > fixed.yaml
	fmt.Print(fixed)
	if !strings.HasSuffix(fixed, "\n") {
		fmt.Println()
	}
	return nil
}

// ── generate ─────────────────────────────────────────────────────────────────

var generateOpts struct {
	save string
}

var generateCmd = &cobra.Command{
	Use:     "generate <requirement...>",
	Short:   "Generate a new workflow from description",
	GroupID: "ai",
	Args:    cobra.MinimumNArgs(1),
	Example: `  seneschal generate "每晚跑测试并通知"
  seneschal generate "deploy to staging" --save deploy.yaml`,
	RunE: func(cmd *cobra.Command, args []string) error {
		return generateWorkflow(strings.Join(args, " "))
	},
}

func init() {
	generateCmd.Flags().StringVarP(&generateOpts.save, "save", "o", "", "save generated YAML to file instead of stdout")
}

// generateWorkflow generates a workflow YAML from a natural-language
// requirement. Prints to stdout (so users can redirect), auto-validates, and
// optionally saves to a file with --save. (Former cmdGenerate.)
func generateWorkflow(requirement string) error {
	if strings.TrimSpace(requirement) == "" {
		return fmt.Errorf("no requirement given")
	}

	assistant, err := buildAssistantFromEnv()
	if err != nil {
		return err
	}
	ctx, cancel := aiContext()
	defer cancel()

	genYAML, err := assistant.Generate(ctx, requirement)
	if err != nil {
		return err
	}

	// Validate and report (non-fatal — print the YAML regardless so the user
	// can edit it).
	if wf, perr := workflow.Parse([]byte(genYAML)); perr == nil {
		if errs := wf.Validate(); len(errs) == 0 {
			fmt.Fprintf(os.Stderr, "✅ Generated workflow '%s' is valid (%d steps)\n", wf.Name, len(wf.Steps))
		} else {
			fmt.Fprintf(os.Stderr, "⚠️  Generated workflow has %d validation issue(s):\n", len(errs))
			for _, e := range errs {
				fmt.Fprintf(os.Stderr, "  - %v\n", e)
			}
			fmt.Fprintln(os.Stderr, "Edit the output before using it.")
		}
	} else {
		fmt.Fprintf(os.Stderr, "⚠️  Generated YAML failed to parse: %v\n", perr)
	}

	if generateOpts.save != "" {
		if err := os.WriteFile(generateOpts.save, []byte(genYAML), 0644); err != nil {
			return fmt.Errorf("saving: %w", err)
		}
		fmt.Fprintf(os.Stderr, "💾 Saved to %s\n", generateOpts.save)
		return nil
	}
	// No --save: print YAML to stdout for redirection.
	fmt.Print(genYAML)
	if !strings.HasSuffix(genYAML, "\n") {
		fmt.Println()
	}
	return nil
}
